# SPDX-License-Identifier: LGPL-2.1-or-later
# Copyright © 2017-2018 ANSSI. All rights reserved.

product = "clipos"
recipe = "qemu"

all: bundle run

# Make sure the Debian SDK is available
sdk:
    just ../sdk_debian/all

# Assemble all the other parts composing the CLIP image into a QEMU QCOW disk
# image.
bundle: clear-bundle sdk
    cosmk bundle "{{product}}/{{recipe}}"

# Clear the result of the previous "bundle" action step.
clear-bundle:
    #!/usr/bin/env bash
    repo_root="$(cosmk repo-root-path)"
    version="$(cosmk product-version {{product}})"
    rm -rf "${repo_root}/out/{{product}}/${version}/{{recipe}}/bundle"

run:
    cosmk spawn "{{product}}/{{recipe}}"

# vim: set ts=4 sts=4 sw=4 et ft=make:
