# SPDX-License-Identifier: LGPL-2.1-or-later
# Copyright © 2017 ANSSI. All rights reserved.

product = "clipos"
recipe = "qemu"

all: bundle

# Make sure the SDK is available
sdk:
    just ../sdk/all

# Generate the Core State for the QEMU test image.
bundle: clear-bundle sdk
    cosmk bundle "{{product}}/{{recipe}}"

# Clear the result of the previous "bundle" action step.
clear-bundle:
    #!/usr/bin/env bash
    repo_root="$(cosmk repo-root-path)"
    version="$(cosmk product-version {{product}})"
    rm -rf "${repo_root}/out/{{product}}/${version}/{{recipe}}/bundle"

# vim: set ts=4 sts=4 sw=4 et ft=make:
