# SPDX-License-Identifier: LGPL-2.1-or-later
# Copyright © 2017 ANSSI. All rights reserved.

# CLIP OS QEMU target recipe file

features = [ "bundle" ]
sdk = "clipos/sdk"

[bundle]
steps = [
    "{{repo}}/products/{{product}}/{{recipe}}/bundle.sh"
]

# vim: set ts=4 sts=4 sw=4 et ft=toml:
