# SPDX-License-Identifier: LGPL-2.1-or-later
# Copyright © 2017 ANSSI. All rights reserved.

# CLIP OS QEMU target recipe file

sdk = "clipos/sdk"
actions = [ "bundle" ]

# vim: set ts=4 sts=4 sw=4 et ft=toml:
